language: php
php:
- 5.4
addons:
  postgresql: "9.3"
install:
- pear install pear/PHP_CodeSniffer
- /home/travis/.phpenv/versions/5.5/bin/composer install
- phpenv rehash 

before_script:
- psql -c "CREATE DATABASE eden;" -U postgres -h 127.0.0.1

script:
- phpunit
- phpcs

